language: c
sudo: false
services:
  - docker
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-docker.sh
script: bash -ex ./.travis-docker.sh
env:
  global:
  - PINS="graphql_parser:. graphql:. graphql-async:. graphql-lwt:. graphql-cohttp:."
  matrix:
  - DISTRO="ubuntu-16.04" OCAML_VERSION="4.03" PACKAGE="graphql_parser"
  - DISTRO="ubuntu-16.04" OCAML_VERSION="4.04" PACKAGE="graphql_parser"
  - DISTRO="ubuntu-16.04" OCAML_VERSION="4.05" PACKAGE="graphql_parser"
  - DISTRO="ubuntu-16.04" OCAML_VERSION="4.06" PACKAGE="graphql_parser"
  - DISTRO="ubuntu-16.04" OCAML_VERSION="4.07" PACKAGE="graphql_parser"
  - DISTRO="ubuntu-16.04" OCAML_VERSION="4.03" PACKAGE="graphql"
  - DISTRO="ubuntu-16.04" OCAML_VERSION="4.04" PACKAGE="graphql"
  - DISTRO="ubuntu-16.04" OCAML_VERSION="4.05" PACKAGE="graphql"
  - DISTRO="ubuntu-16.04" OCAML_VERSION="4.06" PACKAGE="graphql"
  - DISTRO="ubuntu-16.04" OCAML_VERSION="4.07" PACKAGE="graphql"
  - DISTRO="ubuntu-16.04" OCAML_VERSION="4.03" PACKAGE="graphql-lwt"
  - DISTRO="ubuntu-16.04" OCAML_VERSION="4.04" PACKAGE="graphql-lwt"
  - DISTRO="ubuntu-16.04" OCAML_VERSION="4.05" PACKAGE="graphql-lwt"
  - DISTRO="ubuntu-16.04" OCAML_VERSION="4.06" PACKAGE="graphql-lwt"
  - DISTRO="ubuntu-16.04" OCAML_VERSION="4.07" PACKAGE="graphql-lwt"
  - DISTRO="ubuntu-16.04" OCAML_VERSION="4.03" PACKAGE="graphql-async"
  - DISTRO="ubuntu-16.04" OCAML_VERSION="4.04" PACKAGE="graphql-async"
  - DISTRO="ubuntu-16.04" OCAML_VERSION="4.05" PACKAGE="graphql-async"
  - DISTRO="ubuntu-16.04" OCAML_VERSION="4.06" PACKAGE="graphql-async"
  - DISTRO="ubuntu-16.04" OCAML_VERSION="4.07" PACKAGE="graphql-async"
  - DISTRO="ubuntu-16.04" OCAML_VERSION="4.03" PACKAGE="graphql-cohttp"
  - DISTRO="ubuntu-16.04" OCAML_VERSION="4.04" PACKAGE="graphql-cohttp"
  - DISTRO="ubuntu-16.04" OCAML_VERSION="4.05" PACKAGE="graphql-cohttp"
  - DISTRO="ubuntu-16.04" OCAML_VERSION="4.06" PACKAGE="graphql-cohttp"
  - DISTRO="ubuntu-16.04" OCAML_VERSION="4.07" PACKAGE="graphql-cohttp"
